name: Scheduled Python Script

on:
  schedule:
    - cron: '40 13 * * *' 

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python main.py
