name: Daily Refresh POST

on:
  schedule:
    - cron: '30 9 * * *'  # 3:00 PM IST = 09:30 UTC

jobs:
  post-refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to refresh endpoint
        run: |
          curl -X POST https://localfarmermarket.onrender.com/rates/refresh
